// @ts-nocheck
module.exports = {
  types: [
    ["feat", "🌟", "新增功能 (New feature)", "新的功能或特性 (New feature or functionality)"],
    ["fix", "🔨", "问题修复 (Bug fix)", "修复问题 (Fix a bug)"],
    ["docs", "📚", "文档更新 (Documentation)", "仅文档变更 (Documentation only)"],
    ["style", "🎨", "代码格式 (Code style)", "不影响代码含义的变更：空格、格式化、缺少分号等 (Changes that do not affect code semantics: whitespace, formatting, missing semicolons, etc.)"],
    ["refactor", "🧱", "代码重构 (Refactor)", "代码重构，无删减功能特性 (Code refactoring without adding or removing features)"],
    ["perf", "🚀", "性能优化 (Performance)", "提升性能的代码变更 (Performance improvements)"],
    ["test", "🦾", "测试相关 (Tests)", "新增或修正测试用例 (Adding or fixing tests)"],
    ["build", "📀", "构建系统 (Build)", "影响构建系统的变更 (Changes affecting the build system)"],
    ["ci", "⌛️", "持续集成 (CI)", "CI 配置文件及脚本的变更 (Changes to CI configuration files and scripts)"],
    ["chore", "🍿", "日常事务 (Chores)", "其他变更：依赖管理、包管理器配置、脚本调整、工具配置等 (Other changes: dependency management, package manager config, scripts, tooling config, etc.)"],
    ["release", "🎉", "版本发布 (Release)", "发布新版本 (Release a new version)"],
    ["revert", "🔙", "版本回退 (Revert)", "回退上一次提交 (Revert the previous commit)"],
  ].map(([value, icon, name, description]) => ({
    value,
    name: icon.padEnd(4) + value.padEnd(10) + name.padEnd(24) + description,
  })),
  scopes: [
    { name: "kit（根包 @pawover/kit：entry/、根 package.json 发布与 build）", value: "kit" },
    { name: "kit-hooks（React / Alova hooks）", value: "kit-hooks" },
    { name: "kit-utils（静态工具类）", value: "kit-utils" },
    { name: "kit-types（纯类型工具包）", value: "kit-types" },
    { name: "kit-zod（Zod v4 schema）", value: "kit-zod" },
    { name: "kit-eslint-rules（ESLint 规则集）", value: "kit-eslint-rules" },
    { name: "release（发布流程：scripts 发布脚本、.changeset/、release.yml）", value: "release" },
    { name: "ci（CI/CD：.github/workflows、CI 脚本）", value: "ci" },
    { name: "test（测试：test/ 目录 unit / integration / types）", value: "test" },
    { name: "docs（文档：docs/、README、AGENTS.md、CONTRIBUTING）", value: "docs" },
    { name: "tooling（工具配置：eslint / tsconfig / prettier / cz / turbo / tsdown）", value: "tooling" },
    { name: "deps（依赖变更：pnpm-lock.yaml、依赖增删升级）", value: "deps" },
  ],
  messages: {
    type: "请选择本次提交的变更类型 (Select the type of change):",
    scope: "请输入本次变更的影响范围，可选 (Enter the scope of this change, optional):",
    customScope: "请输入本次变更的影响范围 (Enter the scope of this change):",
    subject: "请输入本次变更的简短描述 (Enter a short description of this change):",
    body: "请输入本次变更的详细描述，使用 \"|\" 符号进行换行，可选 (Enter a detailed description, use \"|\" for line breaks, optional):",
    breaking: "请列出任何破坏性变更，可选 (List any breaking changes, optional):\n",
    footer: "请输入本次提交关闭的 Issue，例如：#31, #34，可选 (Enter the Issue(s) closed by this commit, e.g. #31, #34, optional):",
    confirmCommit: "确认提交以上内容？(Confirm the commit above?)",
  },
  allowCustomScopes: true,
  allowBreakingChanges: ["feat", "fix"],
  subjectLimit: 120,
};
