export const MIME = {
  css: "text/css",
  csv: "text/csv",
  doc: "app/vnd.openxmlformats-officedocument.wordprocessingml.document",
  dxf: ".dxf",
  gif: "image/gif",
  html: "text/html",
  jpeg: "image/jpeg",
  jpg: "image/jpg",
  js: "text/javascript",
  json: "app",
  mp3: "audio/mpeg",
  mp4: "video/mp4",
  png: "image/png",
  txt: "text/plain",
  xls_a: "app/vnd.ms-excel",
  xls_b: "application/vnd.ms-excel",
  xlsx_a: "app/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  xlsx_b: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
} as const;
