import preset from "./preset.ts";

export default {
  // Base Rules
  "vue/comment-directive": 2,
  "vue/jsx-uses-vars": 2,
  // Priority A: Essential
  "vue/multi-word-component-names": 0,
  "vue/no-arrow-functions-in-watch": 2,
  "vue/no-async-in-computed-properties": 2,
  "vue/no-child-content": 2,
  "vue/no-computed-properties-in-data": 2,
  "vue/no-dupe-keys": 2,
  "vue/no-dupe-v-else-if": 2,
  "vue/no-duplicate-attributes": 2,
  "vue/no-export-in-script-setup": 2,
  "vue/no-mutating-props": 2,
  "vue/no-parsing-error": 2,
  "vue/no-ref-as-operand": 2,
  "vue/no-reserved-component-names": 2,
  "vue/no-reserved-keys": 2,
  "vue/no-reserved-props": 2,
  "vue/no-shared-component-data": 2,
  "vue/no-side-effects-in-computed-properties": 2,
  "vue/no-template-key": 2,
  "vue/no-textarea-mustache": 2,
  "vue/no-unused-components": 1,
  "vue/no-unused-vars": 1,
  "vue/no-use-computed-property-like-method": 2,
  "vue/no-use-v-if-with-v-for": 2,
  "vue/no-useless-template-attributes": 2,
  "vue/no-v-text-v-html-on-component": 2,
  "vue/require-component-is": 2,
  "vue/require-prop-type-constructor": 2,
  "vue/require-render-return": 2,
  "vue/require-v-for-key": 2,
  "vue/require-valid-default-prop": 2,
  "vue/return-in-computed-property": 2,
  "vue/return-in-emits-validator": 2,
  "vue/use-v-on-exact": 2,
  "vue/valid-attribute-name": 2,
  "vue/valid-define-emits": 2,
  "vue/valid-define-props": 2,
  "vue/valid-next-tick": 2,
  "vue/valid-template-root": 2,
  "vue/valid-v-bind": 2,
  "vue/valid-v-cloak": 2,
  "vue/valid-v-else-if": 2,
  "vue/valid-v-else": 2,
  "vue/valid-v-for": 2,
  "vue/valid-v-html": 2,
  "vue/valid-v-if": 2,
  "vue/valid-v-model": 2,
  "vue/valid-v-on": 2,
  "vue/valid-v-once": 2,
  "vue/valid-v-pre": 2,
  "vue/valid-v-show": 2,
  "vue/valid-v-slot": 2,
  "vue/valid-v-text": 2,

  // Priority A: Essential for Vue.js 3.x
  "vue/no-deprecated-data-object-declaration": 2,
  "vue/no-deprecated-delete-set": 2,
  "vue/no-deprecated-destroyed-lifecycle": 2,
  "vue/no-deprecated-dollar-listeners-api": 2,
  "vue/no-deprecated-dollar-scopedslots-api": 2,
  "vue/no-deprecated-events-api": 2,
  "vue/no-deprecated-filter": 2,
  "vue/no-deprecated-functional-template": 2,
  "vue/no-deprecated-html-element-is": 2,
  "vue/no-deprecated-inline-template": 2,
  "vue/no-deprecated-model-definition": 2,
  "vue/no-deprecated-props-default-this": 2,
  "vue/no-deprecated-router-link-tag-prop": 2,
  "vue/no-deprecated-scope-attribute": 2,
  "vue/no-deprecated-slot-attribute": 2,
  "vue/no-deprecated-slot-scope-attribute": 2,
  "vue/no-deprecated-v-bind-sync": 2,
  "vue/no-deprecated-v-is": 2,
  "vue/no-deprecated-v-on-native-modifier": 2,
  "vue/no-deprecated-v-on-number-modifiers": 2,
  "vue/no-deprecated-vue-config-keycodes": 2,
  "vue/no-expose-after-await": 2,
  "vue/no-lifecycle-after-await": 2,
  "vue/no-v-for-template-key-on-child": 2,
  "vue/no-watch-after-await": 2,
  "vue/prefer-import-from-vue": 2,
  "vue/require-slots-as-functions": 2,
  "vue/require-toggle-inside-transition": 2,
  "vue/valid-define-options": 2,
  "vue/valid-v-is": 2,
  "vue/valid-v-memo": 2,

  // Priority A: Essential for Vue.js 2.x
  "vue/no-custom-modifiers-on-v-model": 2,
  "vue/no-multiple-template-root": 0,

  // Priority B: Strongly Recommended
  "vue/attribute-hyphenation": [2, "never", { ignore: [] }],
  "vue/component-definition-name-casing": 2,
  "vue/first-attribute-linebreak": [2, { singleline: "beside", multiline: "below" }],
  "vue/html-closing-bracket-newline": 2,
  "vue/html-closing-bracket-spacing": 2,
  "vue/html-end-tags": 2,
  "vue/html-indent": 2,
  "vue/html-quotes": 2,
  "vue/html-self-closing": [2, { html: { void: "always", normal: "always", component: "always" }, svg: "always", math: "always" }],
  "vue/max-attributes-per-line": 2,
  "vue/multiline-html-element-content-newline": 2,
  "vue/mustache-interpolation-spacing": 2,
  "vue/no-multi-spaces": 2,
  "vue/no-spaces-around-equal-signs-in-attribute": 2,
  "vue/no-template-shadow": 2,
  "vue/one-component-per-file": 2,
  "vue/prop-name-casing": 2,
  "vue/require-default-prop": 0,
  "vue/require-prop-types": 2,
  "vue/singleline-html-element-content-newline": 2,
  "vue/v-bind-style": 2,
  "vue/v-on-style": 2,
  "vue/v-slot-style": 2,

  // Priority B: Strongly Recommended for Vue.js 3.x
  "vue/require-explicit-emits": 2,
  "vue/v-on-event-hyphenation": [2, "never", { autofix: true }],

  // Priority C: Recommended
  "vue/attributes-order": 2,
  "vue/block-order": [2, { order: ["script:not([setup])", "script[setup]", "template", "style[scoped]", "style:not([scoped])"] }],
  "vue/no-lone-template": 2,
  "vue/no-multiple-slot-args": 2,
  "vue/no-required-prop-with-default": 2,
  "vue/no-v-html": 0,
  "vue/order-in-components": 2,
  "vue/this-in-template": 2,

  // Uncategorised
  "vue/block-lang": 0,
  "vue/block-tag-newline": 2,
  "vue/component-api-style": 2,
  "vue/component-name-in-template-casing": [2, "PascalCase", { registeredComponentsOnly: false }],
  "vue/component-options-name-casing": [2, "PascalCase"],
  "vue/custom-event-name-casing": [2, "camelCase", { ignores: [] }],
  "vue/define-emits-declaration": 0,
  "vue/define-macros-order": [2, { order: ["defineOptions", "defineProps", "defineSlots", "defineEmits"], defineExposeLast: false }],
  "vue/define-props-declaration": 0,
  "vue/define-props-destructuring": 0,
  "vue/enforce-style-attribute": 0,
  "vue/html-button-has-type": 0,
  "vue/html-comment-content-newline": 2,
  "vue/html-comment-content-spacing": 2,
  "vue/html-comment-indent": 2,
  "vue/match-component-file-name": 0,
  "vue/match-component-import-name": 2,
  "vue/max-lines-per-block": 2,
  "vue/max-props": 0,
  "vue/max-template-depth": 0,
  "vue/new-line-between-multi-line-property": 0,
  "vue/next-tick-style": 0,
  "vue/no-bare-strings-in-template": 0,
  "vue/no-boolean-default": 0,
  "vue/no-duplicate-attr-inheritance": 2,
  "vue/no-duplicate-class-names": 2,
  "vue/no-empty-component-block": 2,
  "vue/no-import-compiler-macros": 0,
  "vue/no-multiple-objects-in-class": 0,
  "vue/no-negated-v-if-condition": 0,
  "vue/no-potential-component-option-typo": 0,
  "vue/no-ref-object-reactivity-loss": 0,
  "vue/no-restricted-block": 0,
  "vue/no-restricted-call-after-await": 0,
  "vue/no-restricted-class": 0,
  "vue/no-restricted-component-names": 0,
  "vue/no-restricted-component-options": 0,
  "vue/no-restricted-custom-event": 0,
  "vue/no-restricted-html-elements": 0,
  "vue/no-restricted-props": 0,
  "vue/no-restricted-static-attribute": 0,
  "vue/no-restricted-v-bind": 0,
  "vue/no-restricted-v-on": 0,
  "vue/no-root-v-if": 0,
  "vue/no-setup-props-reactivity-loss": 0,
  "vue/no-static-inline-styles": 0,
  "vue/no-template-target-blank": 0,
  "vue/no-this-in-before-route-enter": 2,
  "vue/no-undef-components": 0,
  "vue/no-undef-properties": 0,
  "vue/no-unsupported-features": 0,
  "vue/no-unused-emit-declarations": 0,
  "vue/no-unused-properties": 1,
  "vue/no-unused-refs": 1,
  "vue/no-use-v-else-with-v-for": 0,
  "vue/no-useless-mustaches": 2,
  "vue/no-useless-v-bind": 2,
  "vue/no-v-text": 0,
  "vue/padding-line-between-blocks": 2,
  "vue/padding-line-between-tags": 0,
  "vue/padding-lines-in-component-definition": 0,
  "vue/prefer-define-options": 2,
  "vue/prefer-prop-type-boolean-first": 2,
  "vue/prefer-separate-static-class": 0,
  "vue/prefer-true-attribute-shorthand": 0,
  "vue/prefer-use-template-ref": 2,
  "vue/require-default-export": 2,
  "vue/require-direct-export": 2,
  "vue/require-emit-validator": 0,
  "vue/require-explicit-slots": 2,
  "vue/require-expose": 2,
  "vue/require-macro-variable-name": [2, { defineProps: "props", defineEmits: "emits", defineSlots: "slots", useSlots: "slots", useAttrs: "attrs" }],
  "vue/require-name-property": 0,
  "vue/require-prop-comment": 0,
  "vue/require-typed-object-prop": 0,
  "vue/require-typed-ref": 2,
  "vue/restricted-component-names": 0,
  "vue/script-indent": [0, preset.indent, { baseIndent: 0, switchCase: 1, ignores: [] }],
  "vue/slot-name-casing": 2,
  "vue/sort-keys": 0,
  "vue/static-class-names-order": 0,
  "vue/v-for-delimiter-style": 0,
  "vue/v-if-else-key": 0,
  "vue/v-on-handler-style": 0,

  // Extension Rules
  "vue/array-bracket-newline": [2, "consistent"],
  "vue/array-bracket-spacing": 2,
  "vue/array-element-newline": [2, "consistent"],
  "vue/arrow-spacing": 2,
  "vue/block-spacing": 2,
  "vue/brace-style": 2,
  "vue/camelcase": 0,
  "vue/comma-dangle": [2, "always-multiline"],
  "vue/comma-spacing": 2,
  "vue/comma-style": 2,
  "vue/dot-location": 0,
  "vue/dot-notation": 0,
  "vue/eqeqeq": 2,
  "vue/func-call-spacing": 2,
  "vue/key-spacing": 2,
  "vue/keyword-spacing": 2,
  "vue/max-len": 0,
  "vue/multiline-ternary": [2, "always-multiline"],
  "vue/no-console": 0,
  "vue/no-constant-condition": 2,
  "vue/no-empty-pattern": 2,
  "vue/no-extra-parens": 0,
  "vue/no-implicit-coercion": [2, { allow: ["!!"] }],
  "vue/no-irregular-whitespace": 2,
  "vue/no-loss-of-precision": 2,
  "vue/no-negated-condition": 0,
  "vue/no-restricted-syntax": 0,
  "vue/no-sparse-arrays": 2,
  "vue/no-useless-concat": 0,
  "vue/object-curly-newline": 2,
  "vue/object-curly-spacing": [2, "always"],
  "vue/object-property-newline": [2, { allowAllPropertiesOnSameLine: true }],
  "vue/object-shorthand": 0,
  "vue/operator-linebreak": [2, "after", { overrides: { "?": "ignore", ":": "ignore", "|": "before" } }],
  "vue/prefer-template": 0,
  "vue/quote-props": [2, "consistent-as-needed"],
  "vue/space-in-parens": 2,
  "vue/space-infix-ops": 2,
  "vue/space-unary-ops": 2,
  "vue/template-curly-spacing": 2,
};
