const metadata = {
  index: [
    "arrayCast",
    "arrayCompete",
    "arrayCounting",
    "arrayDiff",
    "arrayFirst",
    "arrayFork",
    "arrayLast",
    "arrayMerge",
    "arrayPick",
    "arrayReplace",
    "arraySplit",
    "cloneDeep",
    "enumEntries",
    "enumKeys",
    "enumTypeCheck",
    "enumValues",
    "isArray",
    "isAsyncFunction",
    "isBigInt",
    "isBoolean",
    "isClass",
    "isDate",
    "isEqual",
    "isError",
    "isFile",
    "isFunction",
    "isGeneratorFunction",
    "isInteger",
    "isIterable",
    "isMap",
    "isNull",
    "isNumber",
    "isObject",
    "isPromise",
    "isPromiseLike",
    "isRegExp",
    "isSet",
    "isString",
    "isSymbol",
    "isURLSearchParams",
    "isUndefined",
    "isWeakMap",
    "isWeakSet",
    "isWebSocket",
    "isWindow",
    "mapEntries",
    "objectAssign",
    "objectEntries",
    "objectKeys",
    "objectPick",
    "objectSwitch",
    "objectValues",
    "rowsToTree",
    "stringInitialCase",
    "stringReplace",
    "stringToJson",
    "stringToValues",
    "to",
    "treeFilter",
    "treeFind",
    "treeForEach",
    "treeMap",
    "treeToRows",
  ],
  enums: ["BREAK_POINT_TOKENS"],
  hooks: {
    react: ["useCreation", "useLatest", "useMount", "useResponsive", "useUnmount"],
  },
} as const;

export { metadata };
